version: "3.9"

services:
  # No db server since uses MySQLite database.

  see_stuff:
    image: "kimlewcan/rails-see-stuff:1.0.0"
    restart: always
    ports:
      # Example with a database: Port forwarding on Mac:Port on db container
      # Here: IN port for "${HOST} AWS :IN port for "${CONTAINER}
      # 48017 - PORT_ASSIGNED_ON_HOST_FOR_WEB_APP
      # 3000  - PORT_RAILS_WEB_SERVER_DEFAULT
      - "48017:3000"
